[env]
TERM = "xterm-256color"

[window]
opacity = 1
padding.x = 0
padding.y = 0
decorations = "Full"
decorations_theme_variant = "Dark"
startup_mode = "Maximized"
option_as_alt = "OnlyLeft" 

[font]
normal.family = "FiraCode Nerd Font Mono"
bold.family = "FiraCode Nerd Font Mono"
bold.style = "Regular"
italic.family = "FiraCode Nerd Font Mono"
bold_italic.family = "FiraCode Nerd Font Mono"
size = 19.0

[colors]
primary.background = "#000000"
