require("felix.plugins.install")
require('felix.plugins.vscode-theme')
require('felix.plugins.lualine')
require('felix.plugins.nvim-tree')
require('felix.plugins.treesitter')
require('felix.plugins.bufferline')
