require("felix.plugins.install")
require('felix.plugins.gruvbox')
require('felix.plugins.lualine')
require('felix.plugins.nvim-tree')
require('felix.plugins.treesitter')
require('felix.plugins.bufferline')
require('felix.plugins.telescope')
require('felix.plugins.completion')
require('felix.plugins.mason')
require('felix.plugins.lsp_config')
require('felix.plugins.conform')
require('felix.plugins.gitsigns')
require('felix.plugins.blankline')
require('felix.plugins.comment')
-- require('felix.plugins.tabnine')
require('felix.plugins.colorizer')
